apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-performance-heatmap-flask-server
  labels:
    app: high-performance-heatmap-flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-performance-heatmap-flask-server
  template:
    metadata:
      labels:
        app: high-performance-heatmap-flask-server
    spec:
      containers:
      - name: high-performance-heatmap-flask-server
        image: {{image_name_placeholder}}
        env:
        - name: MONGO_CONNECTION_STRING
          value: {{mongo_connection_placeholder}}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: githubdockerregistry
