apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hiri-heatmap-test
  namespace: hiri
spec:
  rules:
  - host: my-test-host.test.fedcloud.eu
    http:
      paths:
      - backend:
          serviceName: ingress-b39b2b7e1bb7c9849ac0f5c8db5d0b07
          servicePort: 8080
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 131.169.234.105


