apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hiri-heatmap
  namespace: hiri
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-test-host.test.fedcloud.eu
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: test
            port:
              number: 8080
