apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hiri-heatmap-ingress
  namespace: hiri
spec:
  rules:
  - host: hiri-heatmap.test.fedcloud.eu
    http:
      paths:
      - backend:
          serviceName: high-performance-heatmap-vue-js
          servicePort: 8080
        path: /
        pathType: ImplementationSpecific

