apiVersion: v1
kind: Service
metadata:
  name: high-performance-heatmap-vue-js
spec:
  selector:
    app: high-performance-heatmap-vue-js
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
